[
	["B. Henriksson"],
	["Carlos Peña"],
	["D. Wagner"],
	["D. Wagner, J. Rota"],
	["E. Õunap"],
	["Erki Õunap"],
	["G. Balogh"],
	["G. Pohl"],
	["G. Svitra"],
	["H. Takanen"],
	["I. Taal"],
	["J. J. Dombroskie & B. Brunet"],
	["J. J. Dombroskie & C. Whitehouse"],
	["J. J. Dombroskie & J. Walker"],
	["J. J. Dombroskie et al."],
	["J. J. Dombroskie, D. Lawrie & J. Adams"],
	["J. Powell"],
	["J. Rota"],
	["Jadranka Rota"],
	["K .Ruohomäki"],
	["K .Ruohomï¿½ki"],
	["K. Lempa"],
	["M. Deyrup"],
	["S. Gomboc"],
	["S.-H. Yen"],
	["T. Tammaru"],
]
